name: 战双签到

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"

jobs:
  Run_Script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run App
        env:
          id: 2
          token: ${{ secrets.TOKEN }}
        run: node app.js
