name: Gray Raven

on:
  schedule:
    - cron: "30 8 * * *"
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests logging

      - name: Run script
        env:
          gameId: 2
          token: ${{ secrets.TOKEN }}
        run: python main.py
